version: "3"

services:  
  demo_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'demo'
    container_name: demo_mysql
    restart: always
    networks:
      - demo
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  # db_mongo:
  #   image: mongo:3.6.19-xenial
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: 'root'
  #     MONGO_INITDB_ROOT_PASSWORD: '__'
  #     MONGO_INITDB_DATABASE: 'demo'
  #   container_name: demo_mongo
  #   restart: always
  #   networks:
  #     - demo
  #   volumes:
  #     - ./data/mongo:/data/db
  #   ports:
  #     - 27017:27017

  # redis:
  #   image: redis:5
  #   container_name: redis
  #   restart: always
  #   networks:
  #     - demo
  #   ports:
  #     - 6379:6379

  demo_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/manage.py runserver 0.0.0.0:8000
    image: app:latest
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 0
    container_name: demo_app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - demo
    depends_on:
      - demo_mysql


networks:
  demo:
    driver: bridge
